import Head from 'next/head';
import { Header } from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Banxico Visualizer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
    </>
  );
}
